# Constant variables go here

# Supported music services
SERVICE_PANDORA = 1
SERVICE_RHAPSODY = 2
SERVICE_TUNEIN = 3
SERVICE_SPOTIFY = 4
SERVICE_DEEZER = 5
SERVICE_NAPSTER = 6
SERVICE_IHEARTRADIO = 7
SERVICE_SIRIUSXM = 8
SERVICE_SOUNDCLOUD = 9
SERVICE_TIDAL = 10
SERVICE_FUTURE = 11
SERVICE_RDIO = 12
SERVICE_AMAZON = 13
SERVICE_FUTURE_2 = 14
SERVICE_MOODMIX = 15
SERVICE_JUKE = 16
SERVICE_FUTURE_3 = 17
SERVICE_QQ = 18

# Music sources
SOURCE_LOCALUSB = 1024
SOURCE_HEOS_PLAYLIST = 1025
SOURCE_HEOS_HISTORY = 1026
SOURCE_HEOS_AUX = 1027
SOURCE_HEOS_FAVORITES = 1028

# HEOS Defaults
HEOS_PORT = 1255
